#!/bin/bash

if [ -n "$1" ]; then
  session_name="$1"
else
  session_name="default"
fi

# Create a new session with the given name if it does not exist.
if ! tmux has-session -t "=$session_name" >/dev/null; then

  # By overriding this var, you can change the root of the bootstrap files.
  TMUXSH_BOOTSTRAPS_ROOT=${TMUXSH_BOOTSTRAPS_ROOT:=$XDG_CONFIG_HOME/tmux/bootstraps}

  bootstrap="$TMUXSH_BOOTSTRAPS_ROOT/$session_name".sh
  if [ -f "$bootstrap" ]; then
    tmux new-session -d -s "$session_name" sh "$bootstrap"
  else
    tmux new-session -d -s "$session_name"
  fi
fi

if [ -z "$TMUX" ]; then
  tmux attach -t "$session_name"
else
  tmux switch-client -t "$session_name"
fi
